import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Javanese } from 'next/font/google'
import StyledJsxRegistry from './registry'
import Navbar from '../components/Navbar'

const noto = Noto_Sans_Javanese({ weight: '400', subsets: ['javanese'] })

export const metadata: Metadata = {
  title: 'Revealers Media',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{maxWidth: '1500px', margin: '0 auto'}} className={noto.className}>
        <StyledJsxRegistry>
          <div className='flex min-h-screen p-2'>
            <Navbar />
            {children}
          </div>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
