import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledJsxRegistry from './registry'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Revealers Media',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <div className='flex min-h-screen'>
            <Navbar />
            {children}
          </div>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
